# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Generating randomly chosen probabilities for aem-matrix
#'
#'Function written in \code{C++} for generating a set of randomly chosen
#'probabilities for the aem-Matrix.
#'@param n_categories Integer for the number of categories in the data. Must be
#'at least 2.
#'@return Returns a matrix for the assignment errors (AEM) with randomly
#'generated probabilities. The generated probabilities are in line with
#'the assumption of weak superiority.
#'@importFrom Rcpp sourceCpp
#'@useDynLib iotarelr
get_random_start_values_p <- function(n_categories) {
    .Call('_iotarelr_get_random_start_values_p', PACKAGE = 'iotarelr', n_categories)
}

#'Generating randomly chosen probabilities for categorical sizes
#'
#'Function written in \code{C++} for generating a set of randomly chosen
#'probabilities describing the size of the different classes. The
#'probabilities describe the relative frequencies of the categories in the data.
#'@param n_categories Integer for the number of categories in the data. Must be
#'at least 2.
#'@return Returns a vector of randomly chosen categorical sizes.
get_random_start_values_class_sizes <- function(n_categories) {
    .Call('_iotarelr_get_random_start_values_class_sizes', PACKAGE = 'iotarelr', n_categories)
}

#' Estimating log-likelihood
#'
#' Function written in \code{C++} estimating the log-likelihood of a given
#' parameter set.
#'
#' @param categorial_sizes \code{Vector} containing the sizes of the different
#' categories. That is amount of a category on all cases.
#' @param aem \code{Matrix} in aem form. This matrix reports the truth category
#' in the rows and the assigned categories in the columns. The cells represent
#' the probabilities that a coding unit of category i is assigned to category j.
#' @param obs_pattern_shape \code{Matrix} containing the unique patterns found
#' in the data. Ideally this matrix is generated by the function
#' \code{\link{get_patterns}}.
#' @param obs_pattern_frq \code{Vector} containing the frequencies of the
#' patterns. Ideally it is generated by the the function
#' \code{\link{get_patterns}}.
#' @param categorical_levels \code{Vector} containing all possible categories of
#' the content analysis.
#' @return Returns the log-likelihood as a single numeric value.
fct_log_likelihood_c <- function(categorial_sizes, aem, obs_pattern_shape, obs_pattern_frq, categorical_levels) {
    .Call('_iotarelr_fct_log_likelihood_c', PACKAGE = 'iotarelr', categorial_sizes, aem, obs_pattern_shape, obs_pattern_frq, categorical_levels)
}

#'Parameter estimation via EM-Algorithm
#'
#'Function written in \code{C++} for estimating the parameters of the model
#'via Expectation-Maximization(EM)-algorithm.
#' @param obs_pattern_shape \code{Matrix} containing the unique patterns found
#' in the data. Ideally this matrix is generated by the function
#' \code{\link{get_patterns}}.
#' @param obs_pattern_frq \code{Vector} containing the frequencies of the
#' patterns. Ideally it is generated by the the function
#' \code{\link{get_patterns}}.
#' @param obs_internal_count \code{Matrix} containing the relative frequencies
#' of each category within each pattern. Ideally this matrix is generated by
#' the function \code{\link{get_patterns}}.
#' @param categorical_levels \code{Vector} containing all possible categories of
#' the content analysis.
#'@param random_starts Integer for determining how often the algorithm should
#'restart with randomly chosen values for the aem matrix and the categorical
#'sizes.
#'@param max_iterations Integer for determining the maximum number of iterations
#'for each random start.
#'@param rel_convergence Double for determining the convergence criterion. The
#'algorithm stops if the relative change is smaller than this criterion.
#'@param trace \code{TRUE} for printing progress information on the console.
#'\code{FALSE} if this information should not be printed.
#'@return Function returns a \code{List} with the estimated parameter sets for
#'every random start. Every parameter set contains the following components:
#'\item{log_likelihood}{Log-likelihood of the estimated solution.}
#'\item{aem}{Estimated assignment-error-matrix (aem). The rows represent the
#'true categories while the columns stand for the assigned categories. The cells
#'describe the probability that a coding unit of category i is assigned to
#'category j.}
#'\item{categorial_sizes}{\code{Vector} of estimated sizes for each
#'category.}
#'\item{convergence}{If the algorithm converged within the iteration limit
#'\code{TRUE}. \code{FALSE} in every other case.}
#'\item{iteration}{Number of iterations when the algorithm was terminated.}
#'@export
EM_algo_c <- function(obs_pattern_shape, obs_pattern_frq, obs_internal_count, categorical_levels, random_starts, max_iterations, rel_convergence, trace) {
    .Call('_iotarelr_EM_algo_c', PACKAGE = 'iotarelr', obs_pattern_shape, obs_pattern_frq, obs_internal_count, categorical_levels, random_starts, max_iterations, rel_convergence, trace)
}

